from enum import StrEnum, auto


class V0042NodeStatesItem(StrEnum):
    ALLOCATED = auto()
    CLOUD = auto()
    COMPLETING = auto()
    DOWN = auto()
    DRAIN = auto()
    DYNAMIC_FUTURE = auto()
    DYNAMIC_NORM = auto()
    ERROR = auto()
    FAIL = auto()
    FUTURE = auto()
    IDLE = auto()
    INVALID = auto()
    INVALID_REG = auto()
    MAINTENANCE = auto()
    MIXED = auto()
    NOT_RESPONDING = auto()
    PLANNED = auto()
    POWERED_DOWN = auto()
    POWERING_DOWN = auto()
    POWERING_UP = auto()
    POWER_DOWN = auto()
    POWER_DRAIN = auto()
    POWER_UP = auto()
    REBOOT_CANCELED = auto()
    REBOOT_ISSUED = auto()
    REBOOT_REQUESTED = auto()
    RESERVED = auto()
    RESUME = auto()
    UNDRAIN = auto()
    UNKNOWN = auto()
