from enum import StrEnum, auto


class V0042ReservationFlagsItem(StrEnum):
    ALL_NODES = auto()
    ANY_NODES = auto()
    DAILY = auto()
    DURATION_MINUS = auto()
    DURATION_PLUS = auto()
    FLEX = auto()
    HOURLY = auto()
    IGNORE_JOBS = auto()
    MAGNETIC = auto()
    MAINT = auto()
    NO_DAILY = auto()
    NO_FLEX = auto()
    NO_HOLD_JOBS_AFTER_END = auto()
    NO_HOURLY = auto()
    NO_IGNORE_JOBS = auto()
    NO_MAINT = auto()
    NO_PART_NODES = auto()
    NO_PURGE_COMP = auto()
    NO_STATIC = auto()
    NO_USER_DELETE = auto()
    NO_WEEKDAY = auto()
    NO_WEEKEND = auto()
    NO_WEEKLY = auto()
    OVERLAP = auto()
    PART_NODES = auto()
    PURGE_COMP = auto()
    REOCCURRING = auto()
    REPLACE = auto()
    SKIP = auto()
    SPEC_NODES = auto()
    STATIC = auto()
    TIME_FLOAT = auto()
    USER_DELETE = auto()
    WEEKDAY = auto()
    WEEKEND = auto()
    WEEKLY = auto()
