from enum import StrEnum, auto


class V0042JobStateItem(StrEnum):
    BOOT_FAIL = auto()
    CANCELLED = auto()
    COMPLETED = auto()
    COMPLETING = auto()
    CONFIGURING = auto()
    DEADLINE = auto()
    FAILED = auto()
    LAUNCH_FAILED = auto()
    NODE_FAIL = auto()
    OUT_OF_MEMORY = auto()
    PENDING = auto()
    POWER_UP_NODE = auto()
    PREEMPTED = auto()
    RECONFIG_FAIL = auto()
    REQUEUED = auto()
    REQUEUE_FED = auto()
    REQUEUE_HOLD = auto()
    RESIZING = auto()
    RESV_DEL_HOLD = auto()
    REVOKED = auto()
    RUNNING = auto()
    SIGNALING = auto()
    SPECIAL_EXIT = auto()
    STAGE_OUT = auto()
    STOPPED = auto()
    SUSPENDED = auto()
    TIMEOUT = auto()
