from enum import StrEnum, auto


class V0042JobFlagsItem(StrEnum):
    ACCRUE_COUNT_CLEARED = auto()
    BACKFILL_ATTEMPTED = auto()
    CRON_JOB = auto()
    DEPENDENT = auto()
    EXACT_CPU_COUNT_REQUESTED = auto()
    EXACT_MEMORY_REQUESTED = auto()
    EXACT_TASK_COUNT_REQUESTED = auto()
    GRES_BINDING_DISABLED = auto()
    GRES_BINDING_ENFORCED = auto()
    HAS_STATE_DIRECTORY = auto()
    HETEROGENEOUS_JOB = auto()
    JOB_ACCRUE_TIME_RESET = auto()
    JOB_KILL_HURRY = auto()
    JOB_WAS_RUNNING = auto()
    KILL_INVALID_DEPENDENCY = auto()
    MAGNETIC = auto()
    NO_KILL_INVALID_DEPENDENCY = auto()
    PARTITION_ASSIGNED = auto()
    PREFER_MINIMUM_NODE_COUNT = auto()
    SCHEDULING_ATTEMPTED = auto()
    SEND_JOB_ENVIRONMENT = auto()
    SIBLING_CLUSTER_UPDATE_ONLY = auto()
    SKIP_TRES_STRING_ACCOUNTING = auto()
    SPREAD_JOB = auto()
    STEPMGR_ENABLED = auto()
    TESTING_BACKFILL = auto()
    TESTING_WHOLE_NODE_BACKFILL = auto()
    TEST_NOW_ONLY = auto()
    TOP_PRIORITY_JOB = auto()
    USING_DEFAULT_ACCOUNT = auto()
    USING_DEFAULT_PARTITION = auto()
    USING_DEFAULT_QOS = auto()
    USING_DEFAULT_WCKEY = auto()
